$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string

  ref:
    type: object
    properties:
      url:
        type: string
      species:
        type: string
      build:
        type: string
      release:
        type: integer
    required:
      - url
      - species
      - build
      - release

  filtering:
    type: object
    properties:
      vqsr:
        type: boolean
      hard:
        type: object
        properties:
          snvs:
            type: object
            additionalProperties: {}
          indels:
            type: object
            additionalProperties: {}
        required:
          - snvs
          - indels
      vqsr_resources:
        type: object
        additionalProperties: {}
      vqsr_annotation_filters_snp:
        type: string
      vqsr_annotation_filters_indels:
        type: string
    required:
      - vqsr
      - hard

  processing:
    type: object
    properties:
      remove-duplicates:
        type: boolean
      restrict-regions:
        type: string
      region-padding:
        type: integer
    required:
      - remove-duplicates

  params:
    type: object
    properties:
      library:
        type: string   ## 1) wgs - WholeGenomeSeq; 2) wes - WholeExomeSeq
                         ## For deepVariant can be pacbio and hybrid (pacbio and illumina)
      algorithm:
        type: string   ## 1) gatk; 2) deepvariant
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
    required:
      - gatk
      - picard
      - library
      - algorithm


required:
  - samples
  - units
  - ref
  - filtering
  - processing
  - params
